"""Updated the Pick model

Revision ID: 0f6791defa10
Revises: 7c79838a93d5
Create Date: 2024-01-25 17:14:38.978103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6791defa10'
down_revision = '7c79838a93d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('player2_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_column('player2_id')
        batch_op.drop_column('player1_id')

    # ### end Alembic commands ###
