"""Add pick_number to Player

Revision ID: 6ac66acdb825
Revises: b8cdb0d9b6b2
Create Date: 2024-01-18 23:12:46.989272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac66acdb825'
down_revision = 'b8cdb0d9b6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('pick_number')

    # ### end Alembic commands ###
