"""Alter Player model

Revision ID: 99862e31d763
Revises: ec67c49afd65
Create Date: 2024-01-27 08:30:37.941593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99862e31d763'
down_revision = 'ec67c49afd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.Integer(), nullable=True))
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.INTEGER(), nullable=True))
        batch_op.drop_column('seed')

    # ### end Alembic commands ###
