"""Added qf_number to Pick

Revision ID: e5403db6be7f
Revises: 0f6791defa10
Create Date: 2024-01-26 14:47:35.411804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5403db6be7f'
down_revision = '0f6791defa10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.Enum('QF', 'SF', 'F', name='roundtype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick', schema=None) as batch_op:
        batch_op.drop_column('round')

    # ### end Alembic commands ###
